### ISSUE TITLE
Offshore Gen Path Key Change Breaks

### ISSUE THREAD

**Issue by WilliamsTravis** [NREL/reV#181] opened 2020-06-29 18:09 UTC
**Bug Description**
When running offshore the CLI breaks when trying to read the generation file path. It's probably related to this [commit](https://github.com/NREL/reV/commit/a094e60d515b7b4b6cb7b68fcddeb1d97ea1fd91):

**Full Traceback**
Usage: cli_offshore.py [OPTIONS] COMMAND [ARGS]...
Try 'cli_offshore.py --help' for help.

 

Error: no such option: -g

**Expected behavior**
reV calculates generation values for the specified offshore points.

**System (please complete the following information):**
 - OS: Linux
 - Compute hardware: Eagle
 - Version: 0.4.4

**Comment by MRossol** [comment] 2020-06-29 18:17
@WilliamsTravis
Can you point me to a .e file with the exact error message

**Comment by nickwg03** [comment] 2020-06-29 18:19
@MRossol @WilliamsTravis: `/projects/rev/new_projects/reeds_wind_avg/logs/stdout/reeds_wind_avg_offshore_18_3690172.e`

**Comment by MRossol** [comment] 2020-06-29 18:22
Nevermind, I think I found the issue, stupid SBATCH node commands...
I'm updating the conda env now,  can you try in a few
FYI @nickwg03 this should integrate the feature grant finished

**Comment by WilliamsTravis** [comment] 2020-06-29 18:23
Awesome, thanks!

**Comment by nickwg03** [comment] 2020-06-29 18:23
Fantastic work!

**Comment by nickwg03** [comment] 2020-06-29 18:59
@MRossol I'm making progress, but still failing for 1 generation chunk. The error is:

```
ERROR - 2020-06-29 12:50:38,013 [cli_offshore.py:260] : Error running reV offshore CLI.
Traceback (most recent call last):
  File "/shared-projects/rev/modulefiles/gitrepos/reV/reV/offshore/cli_offshore.py", line 258, in <
module>
    main(obj={})
  File "/shared-projects/rev/modulefiles/conda_env/lib/python3.7/site-packages/click/core.py", line
 829, in __call__
    return self.main(*args, **kwargs)
  File "/shared-projects/rev/modulefiles/conda_env/lib/python3.7/site-packages/click/core.py", line
 782, in main
    rv = self.invoke(ctx)
  File "/shared-projects/rev/modulefiles/conda_env/lib/python3.7/site-packages/click/core.py", line
 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/shared-projects/rev/modulefiles/conda_env/lib/python3.7/site-packages/click/core.py", line
 1236, in invoke
    return Command.invoke(self, ctx)
  File "/shared-projects/rev/modulefiles/conda_env/lib/python3.7/site-packages/click/core.py", line
 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/shared-projects/rev/modulefiles/conda_env/lib/python3.7/site-packages/click/core.py", line
 610, in invoke
    return callback(*args, **kwargs)
  File "/shared-projects/rev/modulefiles/conda_env/lib/python3.7/site-packages/click/decorators.py"
, line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/shared-projects/rev/modulefiles/gitrepos/reV/reV/offshore/cli_offshore.py", line 155, in d
irect
    raise e
  File "/shared-projects/rev/modulefiles/gitrepos/reV/reV/offshore/cli_offshore.py", line 151, in d
irect
    fpath_out=fpath_out)
  File "/shared-projects/rev/modulefiles/gitrepos/reV/reV/offshore/offshore.py", line 851, in run
    offshore.save_output(fpath_out)
  File "/shared-projects/rev/modulefiles/gitrepos/reV/reV/offshore/offshore.py", line 395, in save_
output
    self._init_fout(fpath_out)
  File "/shared-projects/rev/modulefiles/gitrepos/reV/reV/offshore/offshore.py", line 419, in _init
_fout
    attrs=ti_attrs)
  File "/shared-projects/rev/modulefiles/gitrepos/reV/reV/offshore/offshore.py", line 417, in _init
_fout
    out._set_meta('meta', self.meta_out, attrs=meta_attrs)
  File "/shared-projects/rev/modulefiles/gitrepos/reV/reV/offshore/offshore.py", line 272, in meta_
out
    return meta
UnboundLocalError: local variable 'meta' referenced before assignment
```

Looks to be occurring here: https://github.com/NREL/reV/blob/master/reV/offshore/offshore.py#L272

Any idea why none of the "if" statements above that line would have been hit?

**Comment by MRossol** [comment] 2020-06-29 19:07
@grantbuster Can you take a look, I'm not very familiar with the offshore module

**Comment by grantbuster** [comment] 2020-06-29 19:39
Are you doing anything funny with the offshore wind farm source data? It looks like the project sites for node0 have only offshore resource pixels but the NN search wasn't able to associate any output wind farms with those points. Here's the line in the log file:

INFO - 2020-06-29 12:50:37,979 [offshore.py:104] : Initialized offshore wind farm aggregation module with 0 onshore resource points, 62204 offshore resource points, and 0 output wind farms.

**Comment by nickwg03** [comment] 2020-06-29 19:41
Not that I'm aware of. Only thing I changed was to use 40 nodes instead of 20 to speed up generation. Perhaps since the gen chunks are smaller it's not finding nearby onshore points?

**Comment by grantbuster** [comment] 2020-06-29 19:47
No that shouldn't make a difference. I'll run that node from ipython when I get a chance and see whats up.

**Comment by grantbuster** [comment] 2020-06-29 21:42
I guess it did make a difference kind of. The code is working as designed but the issue is that node00 has a ton of offshore WTK resource points none of which are associated with wind farms in the the ORCA data "preliminary_orca_results_09042019_JN_gcb_capexmults.csv" because theyre way far away. Here's a map showing whats going on, the blue swath to the left is the WTK resource points in the node00 data. 

![offshore_coordinates](https://user-images.githubusercontent.com/12700356/86058938-f6c34900-ba1e-11ea-803d-606601310c6d.png)

Two things: 

1. We should never be configuring a WTK-reV run with these offshore points as they are too far out and we apparently dont ever use them 
2. I guess reV offshore should be able to handle this, but outputing an empty H5 is not going to be pretty.

**Comment by nickwg03** [comment] 2020-06-29 21:48
@grantbuster Okay that makes sense. So basically we should only be running the WTK points that fall within a certain distance of the ORCA wind farms, then.

**Comment by grantbuster** [comment] 2020-06-29 21:56
Yeah it would be best to only run WTK points that are actually getting used in ORCA wind farms. If a node worker sees a ton of WTK resource sites but no associated wind farms it's saying "what am i supposed to be doing? You gave me exclusively useless offshore points, I don't have anything to do...". Some useless offshore points are okay when mixed with used offshore points, even useless offshore points so long as there are onshore points. But exclusively useless offshore points is not handled right now. 

We can open an issue to handle this in the code but I dont have the bandwidth to make this work right now. It might be simple, it might be a pain, no idea.

**Comment by nickwg03** [comment] 2020-06-29 21:58
@grantbuster Makes sense. I'll go ahead and go back to 20 nodes to avoid this issue, and we can deal with it again in the future. Thanks for tracking it down!

**Comment by grantbuster** [comment] 2020-06-29 22:00
No problem. I'm going to close this issue for now. Feel free to open a new issue for offshore module nodes handling null output. Please include that figure i sent above, as i think its descriptive.

**Closed by grantbuster** 2020-06-29 22:00 UTC
Labels: bug
